/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    sayHello
 * Signature: (IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloJNI_sayHello
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     HelloJNI
 * Method:    sumAndAverage
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_HelloJNI_sumAndAverage
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
